
version: "3"

services:
  nestjs-api:
    build:
      context: .
    image: nestjs
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge