version: "3.9"
services:
  nestjs-api:
    build:
      context: .
      target: install-dependencies
    image: dziedzicgrzegorz/nestjs:latest
    container_name: nestjs-api
    command: npm run start:dev
    volumes:
      - ./src:/user/src/app/src
    ports:
      - "3000:3000"
    networks:
      - my-network
networks:
  my-network:
    driver: bridge