name: Docker Image CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:

  build:

    runs-on: ubuntu-latest
    container:
      image: lucasalt/act_base:latest

    steps:
    - uses: actions/checkout@v3
    # Uruchomienie kontenera na podstawie docker-compose-prod.yml po pushu
    - name: Run Docker Prod
      run: npm run docker:GithubAction